### PR TITLE
Add deprecation message

### PR DESCRIPTION
**Pull request by errietta**
https://github.com/MozillaFoundation/plan/issues/465

### CODE REVIEW

**Comment by secretrobotron** [comment]
@kevzawacki: this look alright to you?
screenshot 2015-07-24 18 31 59

**Comment by KevZawacki** [comment]
Looks great, thanks. 
Do we have an official sunset date for Popcorn Maker? I'd like to add that to the blog post.

**Comment by secretrobotron** [comment]
@errietta ok, got some details about the right string to put in there for you:

> Our tools for teaching the Web are evolving. As of September 30th, Mozilla will no longer provide support for Popcorn Maker. To learn more, read our blog post [http://mzl.la/webmaker-tools-transition].

Pull request incoming.

cc @kevzawacki

**Comment by KevZawacki** [comment]
Also (pardon the last-minute copyedit), can we change "Mozilla will no longer provide support for Popcorn Maker" to "Mozilla will no longer support Popcorn Maker."

**Comment by secretrobotron** [comment]
:+1:

**Comment by secretrobotron** [comment]
@errietta a pull request for you on your branch: https://github.com/errietta/popcorn.webmaker.org/pull/1

**Comment by errietta** [comment]
bah i accidentally merged XD

**Comment by errietta** [comment]
@secretrobotron merged your code in my branch

**Comment by secretrobotron** [comment]
hahaha cool. let's see it build on staging.

**Pull request merged**
