### PR TITLE
Change copy on deprecation page to "retired" from "deprecated" to hel…

### PR DESCRIPTION
**Pull request by cadecairos**
…p non-english readers

### CODE REVIEW

**Comment by benrito** [comment]
@cadecairos can we point people to https://github.com/mozilla/popcorn-editor/issues, where we are working on a white labeled Popcorn Editor? Cc @nokski

**Comment by cadecairos** [comment]
@benrito we totally can and should!

@KevZawacki how can we word this?

**Comment by cadecairos** [comment]
@benrito @KevZawacki I filed #625 to work on linking to popcorn editor

**Comment by benrito** [comment]
I will set up a meeting to discuss; we may want to do some repo magic too

**Comment by KevZawacki** [comment]
@cadecairos @benrito Happy to help with any wording. A bit in the dark on the context. Has someone adopted Popcorn? Are we linking to their iteration?

**Comment by cadecairos** [comment]
@KevZawacki The repo we're linking to is https://github.com/mozilla/popcorn-editor - My understanding is that it's the front-end timeline style editing environment we built for popcorn maker, but made to be embeddable in any context and without the back-end server bits that popcorn maker came with originally.

@benrito did I get that mostly right?

**Comment by benrito** [comment]
Yeah, that’s right; I am going to organize a meeting to figure out the overall approach, but for now it should be OK to add a single line to the README that says something to that effect.

@nolski can probably help come up with an appropriate line.

**Comment by KevZawacki** [comment]
So, the updated copy might read something like: "You can read more about this on our blog. **You can also adopt and tinker with the Popcorn Maker code [here](https://github.com/mozilla/popcorn-editor/issues).**"

**Comment by Nolski** [comment]
@KevZawacki That copy sounds good to me :)

**Comment by cadecairos** [comment]
Closing in favour of #626

**Pull request closed without merging**
