### PR TITLE
Archived locale files

### PR DESCRIPTION
**Pull request by alicoding**

### CODE REVIEW

**Comment by secretrobotron** [comment]
Looks alright to me.
* Do any scripts/deploy things need to change to avoid `webmaker-download-locales`?
* @simonwex this approach look alright to you?

**Comment by simonwex** [comment]
@alicoding could you walk me through this?

**Comment by alicoding** [comment]
@simonwex we want to remove popcorn source file from Transifex so people don't have to translate the project since we are going to archive it here. So, @secretrobotron and I thought we might want to keep the copy of all the translated strings of all languages somewhere and github seems to be the right place for it.

**Comment by simonwex** [comment]
Ah, perfect. Could you also include that somewhere in the README? Something that starts the section "If someone were to adopt Popcorn,  how would they resume where we left off?"

**Pull request merged**
